// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAriiq5LgzHv17l0Zgr0Nlj5qCZRbmTiww',
    appId: '1:436607692940:web:e4eecb69b106530e794ba9',
    messagingSenderId: '436607692940',
    projectId: 'leftover-basket',
    authDomain: 'leftover-basket.firebaseapp.com',
    storageBucket: 'leftover-basket.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RwXSgeixIH-7w6LAolFrJ9t1W5uYyjk',
    appId: '1:436607692940:android:b45f694601fcb3be794ba9',
    messagingSenderId: '436607692940',
    projectId: 'leftover-basket',
    storageBucket: 'leftover-basket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWnD8uD2TlbxGvT6a9iubdU3ocU1JepAo',
    appId: '1:436607692940:ios:95cc5b02f3204ce2794ba9',
    messagingSenderId: '436607692940',
    projectId: 'leftover-basket',
    storageBucket: 'leftover-basket.appspot.com',
    iosClientId: '436607692940-qu8eq9ct2ik3q2btg2v201pr5i0au405.apps.googleusercontent.com',
    iosBundleId: 'com.example.leftoverBasket',
  );
}
